homeassistant:
  customize: !include customize.yaml

  external_url: !secret external_url
  internal_url: "http://192.168.0.51:8123"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

####################################
#  Services
####################################
####################################
frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_named scripts
scene: !include scenes.yaml
zone: !include zone.yaml



http:
  # Add use_x_forwarded_for because of NGINX reverse proxy
  use_x_forwarded_for: true
  # Add trusted_proxies because of NGINX reverse proxy, use Docker subnet
  trusted_proxies:
    - 172.30.32.0/23
  ip_ban_enabled: true
  login_attempts_threshold: 5

#Database for logging
recorder: !include recorder.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

#Apple HomeKit Integration / Siri
homekit:
  filter:
    include_domains:
      - alarm_control_panel
      - camera
    include_entities:
      - binary_sensor.front_door_ding
      - binary_sensor.front_door_motion
      - input_boolean.ring_disable_auto_rearm
      - input_boolean.garbage_day
      - climate.upstairs_thermostat
      - climate.downstairs_thermostat
      - switch.grow_light #plant grow lights
      - switch.family_room_plug #family room floor light
      - switch.light_loft_lamp #loft lamp

# #Honeywell Lyric Thermoostat
lyric:
  client_id: !secret honeywell_CLIENT_ID
  client_secret: !secret honeywell_CLIENT_SECRET

# # Notifications
notify:
#   - platform: discord
#     token: !secret discord_token
  - platform: tts
    name: "Google Home Mini"
    tts_service: tts.google_say
    media_player: media_player.google_home_loft

  - platform: group
    name: "All iPhones"
    services:
      - service: mobile_app_pranavs_iphone_xs
      - service: mobile_app_shekhars_xs_max
      - service: mobile_app_tanujas_iphone

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

# Air Quality Information
iqvia:
  zip_code: !secret my_zipcode

# #PiHole
# pi_hole:
#   - host: 192.168.0.199
#     api_key: !secret pi_hole_api_key

####################################
#  Light Switch
####################################
####################################


####################################
#  Input Select
####################################
####################################

####################################
#  Input Boolean
####################################
####################################

input_boolean:
  #Ring Auto Disarm Disable Switch (sent into Node Red)
  ring_disable_auto_rearm:
    name: Disable Auto Re-Arming
    icon: mdi:stop-circle

  garbage_day:
    name: Garbage Day
    icon: mdi:garbage

####################################
#Communication / Integration
####################################
####################################

#Aeotec Z-stick Gen 5 addition
# zwave:
#   usb_path: /dev/ttyACM0
#   network_key: !secret aeotech_id

#MQTT
mqtt:
  broker: !secret mqtt_url
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: "hass/status"
    payload: "online"
    qos: 0
    retain: false

####################################
# Calendar
####################################
####################################

calendar:
- platform: ics
  calendars:
      - name: "TV Shows"
        url: !secret calendar_tv
        includeAllDay: True


####################################
# Rest Commands
####################################
####################################


####################################
#All BINARY sensor Information
####################################
####################################
# binary_sensor:
#   - platform: ring

####################################
#All Sensor Information
####################################
####################################

sensor:
  #Finance
  - platform: alpha_vantage
    api_key: !secret alpha_vantage
    symbols:
      - symbol: APPL
        name: Apple

  # Dark Sky
  #--------------------
  - platform: darksky
    api_key: !secret darksky_api
    forecast:
      - 0
    hourly_forecast:
      - 0
      - 1
    monitored_conditions:
      - summary
      - icon
      - temperature
      - apparent_temperature
      - precip_type
      - precip_probability
      - precip_accumulation
      - wind_speed
      - wind_gust
      - minutely_summary
      - alerts
    units: us
    scan_interval:
      minutes: 20

  #Honeywell Thermostat data turned into sensors
  - platform: template
    sensors:
      hvac_upstairs_temperature:
        friendly_name: "Upstairs Temperature"
        value_template: '{{ states.climate.upstairs_thermostat.attributes["current_temperature"] }}'
      hvac_upstairs_set_temperature:
        friendly_name: "Upstairs Set Temperature"
        value_template: '{{ states.climate.upstairs_thermostat.attributes["temperature"] }}'
      hvac_upstairs_status:
        friendly_name: "Upstairs HVAC Status"
        value_template: '{{ states.climate.upstairs_thermostat.attributes["hvac_action"] }}'
      hvac_downstairs_temperature:
        friendly_name: "Downstairs Temperature"
        value_template: '{{ states.climate.downstairs_thermostat.attributes["current_temperature"] }}'
      hvac_downstairs_set_temperature:
        friendly_name: "Downstairs Set Temperature"
        value_template: '{{ states.climate.downstairs_thermostat.attributes["temperature"] }}'
      hvac_downstairs_status:
        friendly_name: "Downstairs HVAC Status"
        value_template: '{{ states.climate.downstairs_thermostat.attributes["hvac_action"] }}'

  # History stats for HVAC usage
  - platform: history_stats
    name: Upstairs HVAC Daily Usage
    entity_id: sensor.hvac_upstairs_status
    state: "heating" 
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: Downstairs HVAC Daily Usage
    entity_id: sensor.hvac_downstairs_status
    state: "heating"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  #   #Ring Sensors
  #--------------------
  - platform: ring

  #   #Tautulli API
  #---------------------
  - platform: tautulli
    api_key: !secret tautulli_api
    host: 192.168.0.14
    port: 5107

  - platform: template
    sensors:
      tautulli_count_transcode:
        friendly_name: "Transcode Count"
        value_template: '{{ states.sensor.tautulli.attributes["count_transcode"] }}'
      tautulli_direct_plays:
        friendly_name: "Direct Plays"
        value_template: '{{ states.sensor.tautulli.attributes["direct_plays"] }}'
      tautulli_direct_streams:
        friendly_name: "Direct Streams"
        value_template: '{{ states.sensor.tautulli.attributes["direct_streams"] }}'

      tautulli_wan_bandwidth:
        friendly_name: "WAN Bandwidth"
        value_template: '{{ (states.sensor.tautulli.attributes["wan_bandwidth"] | float / 1024) | round(2) }}'
        unit_of_measurement: "Mbps"
      tautulli_lan_bandwidth:
        friendly_name: "Lan Bandwidth"
        value_template: '{{ (states.sensor.tautulli.attributes["lan_bandwidth"] | float / 1024) | round(2) }}'
        unit_of_measurement: "Mbps"
      tautulli_total_bandwidth:
        friendly_name: "Total Bandwidth"
        value_template: '{{ (states.sensor.tautulli.attributes["total_bandwidth"] | float / 1024) | round(2) }}'
        unit_of_measurement: "Mbps"

####################################
# Media Section
####################################
####################################

#Plex (Drishti) Configuration
plex:
  host: 192.168.0.14
  port: 32400
  token: !secret plex_token
  media_player:
    use_episode_art: true
#-----------------------------------
#Media Players in the House
#-----------------------------------

# media_player:
# ####  Family Room Firestick, connected over ADB
#   - platform: androidtv
#     name: Family Room Firestick
#     host: 192.168.0.32
#     device_class: firetv
#     adb_server_ip: 192.168.0.51
#     state_detection_rules:
#       'com.amazon.tv.launcher':
#         - 'standby'
#       'com.netflix.ninja':
#         - 'media_session_state'
#       'com.ellation.vrv':
#         - 'audio_state'
#       'com.plexapp.android':
#         - 'paused':
#             'media_session_state': 3  # this indentation is important!
#             'wake_lock_size': 1       # this indentation is important!
#         - 'playing':
#             'media_session_state': 3  # this indentation is important!
#         - 'standby'
#       'com.amazon.avod':
#         - 'playing':
#             'wake_lock_size': 4  # this indentation is important!
#         - 'playing':
#             'wake_lock_size': 3  # this indentation is important!
#         - 'paused':
#             'wake_lock_size': 2  # this indentation is important!
#         - 'paused':
#             'wake_lock_size': 1  # this indentation is important!
#         - 'standby'

# # ####  Loft Firestick, connected over ADB
# #   - platform: androidtv
# #     name: Loft Firestick
# #     host: 192.168.0.34
# #     #adb_server_ip: 192.168.0.51
# #     state_detection_rules:
# #       'com.amazon.tv.launcher':
# #         - 'standby'
# #       'com.netflix.ninja':
# #         - 'media_session_state'
# #       'com.ellation.vrv':
# #         - 'audio_state'
# #       'com.plexapp.android':
# #         - 'paused':
# #             'media_session_state': 3  # this indentation is important!
# #             'wake_lock_size': 1       # this indentation is important!
# #         - 'playing':
# #             'media_session_state': 3  # this indentation is important!
# #         - 'standby'
# #       'com.amazon.avod':
# #         - 'playing':
# #             'wake_lock_size': 4  # this indentation is important!
# #         - 'playing':
# #             'wake_lock_size': 3  # this indentation is important!
# #         - 'paused':
# #             'wake_lock_size': 2  # this indentation is important!
# #         - 'paused':
# #             'wake_lock_size': 1  # this indentation is important!
# #         - 'standby'

# # ####  Theater Firestick, connected over ADB
# #   - platform: androidtv
# #     name: Theater Firestick
# #     host: 192.168.0.35
# #     #adb_server_ip: 192.168.0.51
# #     state_detection_rules:
# #       'com.amazon.tv.launcher':
# #         - 'standby'
# #       'com.netflix.ninja':
# #         - 'media_session_state'
# #       'com.ellation.vrv':
# #         - 'audio_state'
# #       'com.plexapp.android':
# #         - 'paused':
# #             'media_session_state': 3  # this indentation is important!
# #             'wake_lock_size': 1       # this indentation is important!
# #         - 'playing':
# #             'media_session_state': 3  # this indentation is important!
# #         - 'standby'
# #       'com.amazon.avod':
# #         - 'playing':
# #             'wake_lock_size': 4  # this indentation is important!
# #         - 'playing':
# #             'wake_lock_size': 3  # this indentation is important!
# #         - 'paused':
# #             'wake_lock_size': 2  # this indentation is important!
# #         - 'paused':
# #             'wake_lock_size': 1  # this indentation is important!
# #         - 'standby'
